name: Actions Workflow

on:
  repository_dispatch: # Used to trigger WF from external sources
    types: [build] # types can be whatever we pass in api dispatches payload. Payload keys: event_type, client_payload
  # schedule:
  #   - cron: "0/5 * * * *"
  #   - cron: "0/6 * * * *"
  push:
    # branches-ignore: # Cannot be used along with branches key
    branches:
      - master
      - 'feature/*'
      - 'feature/**'
      - '!feature/A' # Will ingnore this branch
    # tags-ignore: 
    tags:
      - v1.*
    # paths-ignore:
      # - "docs/**"
    paths:
      - "**.js"
      - "!filename.js"
  pull_request:
    types: [closed, assigned, opened]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Payload dispatches
        run: echo ${{ github.event.client_payload.env }}
      - name: Print GitHub env veriables
        run: |
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
          echo "${{ github.token }}"
          # git clone git@github:$GITHUB_REPOSITORY
          # git checkout $GITHUB_SHA
      - name: List FIles
        run: |
          pwd
          ls -a
      - name: Checkout
        uses: actions/checkout@v1 # Authenticates with GH, fetch and checkout to the commits that triggers this workflow
      - name: List FIles after checkout
        run: |
          pwd
          ls -a
      - name: simple javascript Actions
        id: greet # ID required to reference step outputs in other steps
        uses: actions/hello-world-javascript-action@v1 # Repo name @branch or @release-version or @Commit
        with: # To pass parameters -> Param: Value
          who-to-greet: John
      - name: Log Greeting Time
        run: echo "${{ steps.greet.outputs.time }}"