name: Actions Workflow

on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: simple javascript Actions
        id: greet # ID required to reference step outputs in other steps
        uses: actions/hello-world-javascript-action@v1 # Repo name @branch or @release-version or @Commit
        with: # To pass parameters -> Param: Value
          who-to-greet: John
      - name: Log Greeting Time
        run: echo "{{ steps.greet.outputs.time }}"