name: CI

on:
  pull_request:
    branches: [develop]
  push:
    branches: [develop]

env: 
  working-directory: ./my-app

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache node_modules
        uses: actions/cache@v1
        with:
          path: ~/.npm # where the dependecies cache is stored
          key: ${{ runner.os }}-node-${{ hasFiles('**/package-lock.json') }} # key used to retreive the cache. Hash is used to validate if any package has changed, if so, created new one
          # will look for keys with that prefix when the specified key is not found
          restore-keys: |
            ${{ runner.os }}-node-  
      - name: use NodeJS
        uses: actions/setup-node@v1
        with: 
          node-version: "12.x"
      - run: npm ci
        working-directory: ${{ env.working-directory }}
      - run: npm run format:check
        working-directory: ${{ env.working-directory }}
      - run: npm test -- --coverage
        working-directory: ${{ env.working-directory }}
        env:
          CI: true
      - name: build Project
        if: github.event_name == 'push'
        run: npm run build
        working-directory: ${{ env.working-directory }}

      - name: Deploy Staging
        if: github.event_name == 'push'
        run: npx surge --project ./build --domain silent-apparatus.surge.sh
        working-directory: ${{ env.working-directory }}
        env:
          SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
        