name: Context
on: [push, pull_request]

jobs:
  print-object-contexts:
    runs-on: ubuntu-latest
    timeout-minutes: 360 # Can be placed at step level as well
    continue-on-error: true
    steps: 
    # if there are failures only the ones with valid if conditions will run
    # Unless you use continue_on_error key
      - name: Dump GitHub Context
        env: 
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump Job Context
        env: 
          JOB_CONTEXT: ${{ toJson(job) }}
        run: eccho "$JOB_CONTEXT"
      - name: Dump Steps Context
        if: failure() # True only if previous step has failed. success(), cancel()
        env:
          STEP_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEP_CONTEXT"
      - name: Dump Runner Context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump Strategy Context
        env:
          STRATEGY_CONSTEXT: ${{ toJson(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump Matrix Context
        if: always() # This step will always run
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "$MATRIX_CONTEXT"
  functions:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: Dump using functions
        run: |
          # strings must be within single quotes
          echo ${{ contains('hello', 'll') }}
          echo ${{ startswith('hello', 'he') }}
          echo ${{ endswith('hello', 'lo') }}
          echo ${{ format('Hello {0} {1} {2}', 'worl', '!', '!') }}