name: Container
on: push

jobs:
  node-docker:
    runs-on: ubuntu-latest
    container: node:13.5.0-alpine3.10
    steps: # Steps will run in the container instead of the runner VM
      - name: Log Node version
        run: |
          node -v
          cat /etc/os-release