name: Custom Action
on: push
jobs:
  testing-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/hello-docker
        id: Hello-docker
        with:
          who-ro-greet: "World!!!!!"
      - run: |
          echo "Time: ${{ steps.Hello-docker.outputs.time }}"
          echo $HELLO
      - uses: ./.github/actions/issue
        id: issue
        with:
          token: ${{ secrets.TOKEN_GITTHUB }}
          title: Title
          body: Body
          assignees: 'yarias'
      - run: |
          echo ${{ steps.issue.outputs.issue}}
      - uses: ./.github/actions/hello
        id: Hello
        with:
          who-ro-greet: "World"
      - run: |
          echo "Time: ${{ steps.hello.outputs.time }}"
          echo $HELLO