name: Matrix

on: push

jobs:
  node-version:
    strategy: # Used to run steps in different os, versions, etc
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        node_version: [6, 8, 10]
        include: # Add extra values to exiting configurations
          - os: ubuntu-latest
            node_version: 8
            is_ubuntu_8: "true" # In matrix obj will exist this param only for ubuntu & version 8
        exclude:
          - os: macos-latest
            node_version: 6
          - os: ubuntu-latest
            node_version: 10
      # fail-fast: true # Means that if any other job fails, the other ones will fail also.
      # max-parallel: 2 # By default it tries to run the max dependon on available runner in github
    runs-on: ${{ matrix.os }}
    env:
      IS_UBUNTU_8: ${{ matrix.is_ubuntu_8 }}
    steps:
      - name: Log node version
        run: node -v
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}
      - name: Log node version  
        run: |
          node -v
          echo "$IS_UBUNTU_8"