name: Services
on: push

jobs:
  docker-steps:
    runs-on: ubuntu-latest
    container: 
      image: node:10.18.0-jessie
    steps:
      - name: Log node version
        run: node -v
      - name: Docker Step
        uses: docker://node:12.14.1-alpine3.10 # Uses can be used with docker images as well
        with: # Overwrite the docker image entrypoint
          entrypoint: '/bin/echo'
          args: 'Hello World' # Only one arg can be passed
      - name: Docker Step Log version
        uses: docker://node:12.14.1-alpine3.10 
        with: 
          entrypoint: '/usr/local/bin/node'
          args: -v
      - uses: actions/checkout@v1 # Checkout to access script.sh
      - name: Docker Step run script
        uses: docker://node:12.14.1-alpine3.10 
        with: 
          entrypoint: ./script.sh
          args: "First Arg"
  service-docker_compose:
    runs-on: ubuntu-latest
    services:
      app:
        image: alialaa17/node-api
        ports:
          - 3001:3000
      mongo:
        image: mongo
        ports:
          - 27017:27017
    steps:
      - name: Post a user
        run: "curl -X POST http://localhost:3001/api/user
          -H 'Content-Type: application/json' 
          -d '{\"username\":\"Hello\", \"address\":\"qwerty\"}'"
      - name: Get users
        run: curl http://localhost:3001/api/users